


                        
                     
            
            <div id="NewsArchiev">
                <?php $i=0;?>
                <?php foreach($this->paginator as $post):
                    $i=$i+1;
                ?>  
                           <?php if(($this->paginator->getCurrentPageNumber()==1)&&($i==1)):?>
                 <div id="MainNewsBox">
                        
            <img src="http://www.olivetuniversity.edu/images_articles/files//Architecture5.jpg" alt="Olivet to Establish New College of Architecture, Engineering and Construction"/>                   
                        <h3><?php echo $post->getCreate_time();?></h3>
                            <h2><a href="article.html"><a href="/post/view/<?php echo $post->getId();?>"><?php echo $post->getTitle();?></a></h2>
                            <h4><?php echo nl2br($post->getExcerpt());?> <a href="articles/2015/03/06/926/olivet-university-olivet-to-establish-new-college-of-architecture--engineering-and-construction.htm">Read more</a></h4>
                                                        
                        </div>
            <?php else:?>          
                             <h3><?php echo $post->getCreate_time();?></h3>
                           <h2><a href="article.html"><?php echo $post->getTitle();?></a></h2>
                           <p><?php echo $post->getExcerpt();?></p>
                        
            <?php endif;?>             
        <?php endforeach;?>
                        
												</div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                      <?php

 // add at the end of the file after the table

 echo $this->paginationControl(

     // the paginator object

     $this->paginator,

     // the scrolling style

     'sliding',

     // the partial to use to render the control

     'partial/paginator.phtml',

     // the route to link to when a user clicks a control link

     array(

         'route' => 'category_home'

     )

 );

 ?>   
                        <!-- Numbering End -->
                        
                        
                   