    <!-- Contents Start -->
    <div id="ConWrapLeft">
    	<div id="ConWrapRight">
        	<div id="ContentsWrapper">
            	<div id="Contents">
                	<div id="ConLeft">
			
                        <div id="MainNav">
                            <ul>
                            	
                                <li ><a href="admin_index.html" title="Olivet University Theology">Manage News</a></li>
                                <li ><a href="admin_category.html" title="Olivet University Theology">Manage Categories</a></li>
                                <li class="Current"><a href="index.html" title="Olivet University General News">Go to Frontend</a></li>
				<li class="lastone"><a href="category.html?opt=ocb" title="Olivet University Business">Log Out</a></li>
                            </ul>
                        </div>
                        
			<style>
                            #MainNewsBox li{margin:10px 0}
                            
                        </style>															<!-- MainNews Start -->
                        <div id="MainNewsBox">
			    <h2>Categories</h2>
                            <ul>
                            	<?php foreach($this->categories as $category):?>
                                <li><a><?php echo $category->getName();?></a>
                                - <a href="<?php $this->url("category_edit");?>">Edit</a> - 
                                <a href="<?php $this->url("category_delete");?>">Delete</a>
                                </li>
                                <?php endforeach;?>
                                
                            </ul>
                        </div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                        
                        <br/>
                        
                        <a href="admin_add_category.html">Add Category</a>
                    </div>
                  
