
    <!-- Contents Start -->
    <div id="ConWrapLeft">
    	<div id="ConWrapRight">
        	<div id="ContentsWrapper">
            	<div id="Contents">
                	<div id="ConLeft">
			
                        <div id="MainNav">
                            <ul>
                            	
                                <li ><a href="admin_index.html" title="Olivet University Theology">Manage News</a></li>
                                <li ><a href="admin_category.html" title="Olivet University Theology">Manage Categories</a></li>
                                <li class="Current"><a href="index.html" title="Olivet University General News">Go to Frontend</a></li>
				<li class="lastone"><a href="category.html?opt=ocb" title="Olivet University Business">Log Out</a></li>
                            </ul>
                        </div>
                        
			<style>
                            #MainNewsBox li{margin:10px 0}
                            
                        </style>															<!-- MainNews Start -->
                        <div id="MainNewsBox">
                            <h2>News</h2>
                            <ul>
                                <?php foreach($this->paginator as $post):?>
                                <li><a href="article.html"><?php echo $post->getTitle();?></a>
                                - <a href="admin_edit.html">Edit</a> - <a href="admin_delete.html">Delete</a>
                                </li>
                                <?php endforeach;?>
                                
                            </ul>
                        </div>
                        <!-- NewsArcheive End -->
                        <!-- Numbering Start -->
                         <?php

 // add at the end of the file after the table

 echo $this->paginationControl(

     // the paginator object

     $this->paginator,

     // the scrolling style

     'sliding',

     // the partial to use to render the control

     'partial/paginator.phtml',

     // the route to link to when a user clicks a control link

     array(

         'route' => 'home'

     )

 );

 ?>   
                        <!-- Numbering End -->