
    <!-- Header Start -->
    <div id="HeaderBG">
      <div id="HeaderWrapper">
            <div id="Header">
                <h1><a href="<?php echo $this->url("home")?>" title="Olivet University News"><span class="non_disply"><strong>OLIVET UNIVERSITY NEWS | Olivet News</strong></span></a></h1>
               
		<div id="HeaderSearchBox">
			
				<form name="topsearch" action="search.html" id="top_search_box" onSubmit="return chk_search()">
					
						<input type="text" name="q">
					</form>
				
				 <a href="<?php echo $this->url("login")?>">Admin Login</a>
				
				
                </div>
		
            </div>
        </div>
    </div>