
<!-- Header End -->
<!-- Contents Start -->
<div id="ConWrapLeft">
	<div id="ConWrapRight">
		<div id="ContentsWrapper">
			<div id="Contents">
				<div id="ConLeft">

					<div id="MainNav">
						<ul>

							<li><a href="<?php echo $this->url("post_manage")?>"
								title="Olivet University Theology">Manage News</a></li>
							<li><a href="<?php echo $this->url("category_manage")?>"
								title="Olivet University Theology">Manage Categories</a></li>
							<li class="Current"><a href="<?php echo $this->url("home")?>"
								title="Olivet University General News">Go to Frontend</a></li>
							<li class="lastone"><a href="<?php echo $this->url("home")?>"
								title="Olivet University Business">Log Out</a></li>
						</ul>
					</div>

					<style>
#MainNewsBox li {
	margin: 10px 0
}
</style>
					<!-- MainNews Start -->
					<div id="MainNewsBox">
						<h2>News</h2>
						<ul>
                            	<?php foreach($this->paginator as $post):?>
                                <?php echo $post->getTitle();?></a>
							</br>
							</li>
                                <?php endforeach;?>
                               
                                
                            </ul>
					</div>

					<!-- NewsArcheive End -->
					<!-- Numbering Start -->
					<ul class="NewsNumbering">
						<li><a class='actives' href="/index.htm?page=1"><b>1</b></a></li>
						<li><a href="/index.htm?page=2">2</a></li>
						<li><a href="/index.htm?page=3">3</a></li>
						<li><a href="/index.htm?page=4">4</a></li>
						<li><a href="/index.htm?page=5">5</a></li>
						<li><a href="/index.htm?page=6">6</a></li>
						<li><a href="/index.htm?page=7">7</a></li>
						<li><a href="/index.htm?page=8">8</a></li>
						<li><a href="/index.htm?page=9">Next ></a></li>
					</ul>
					<!-- Numbering End -->